
name: "first workflow"

on:
  push:
  pull_request:
    #if you want to enable for specific branch
    # branches:
    #   - main
    #   - dev
    

jobs:
  lint-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependency
        run: npm ci

  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependency
        run: npm ci

      - name: run test cases of app
        run: npm run test

      
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependency
        run: npm ci

      - name: Make React build
        run: npm run build

      - name: create artifacts
        uses: actions/upload-artifact@v4
        with: 
            name: react-build
            path: dist/
            retention-days: 7